### PR TITLE
Added Mocha tests for core with 100% coverage using Istanbul

### LINKED ISSUE #42: Wrapper does not work when method has more than 3 parameters
I'm not sure if this is a bug or an unimplemented feature. 

Version: `1.6.14`

Clearly if `@Wrapper(...)` is not used on a method, then the method must be of type `(req: Request, res: Response) => any` to work. However, if `@Wrapper(func)` is defined, then the method `method(...)` really could be of any type, as long as `func(method)` is of type  `(req: Request, res: Response) => any`.

Currently, if `method(...)` has up to three parameters, this works. However, if `method(...)` has more than three parameters, then the method returns `null`.

Consider the following:

```typescript
@Controller('path')
export class BigWrapperController {

    @Get('3args')
    @Wrapper(returnAsMessage(1, 1, 1))
    sum3(num1: number, num2: number, num3: number): number {
        return num1 + num2 + num3;
    }

    @Get('4args')
    @Wrapper(returnAsMessage(1, 1, 1, 1))
    sum4(num1: number, num2: number, num3: number, num4: number): number {
        return num1 + num2 + num3 + num4;
    }

}

/**
 * Wrapper that passes its arguments to the method and then handles the
 * request with a 200 status code and the method's return value as a
 * message in the response body.
 * @param args Arguments to be passed to the method
 */
function returnAsMessage(...args: any) {
    return (method: Function): RequestHandler => {
        return (req: Request, res: Response): Response => {
            return res.status(200).json({
                message: method(...args)
            })
        }
    }
}
```

When calling the route `/path/3args`, the response is:
``` typescript
{
    message: 3
}
```
When calling the route `/path/4args`, the response is:
``` typescript
{
    message: null // Should be 4
}
```
Code to reproduce is linked [here](https://gist.github.com/joeykilpatrick/aa16b364421d597e54a433e9184b11c5).

### PR DESCRIPTION
**Pull request by joeykilpatrick**
### Other changes to core

- Broke up decorators.ts into individual files for easier testing
- Refactored to enforce strict typing throughout
- Added `npm run lint` command to run tslint over all files
- Added `npm run test` command to run Mocha tests
- Added `npm run coverage` command to run tests and generate console and HTML coverage reports
- Allowed `@ErrorMiddleware` to also take in an array of `ErrorMiddleware`
- Added `@All` decorator to use a method for all HTTP verbs 
- Added support for multiple `@VERB` decorators on a method
- Closed #42

### CODE REVIEW

**Comment by seanpmaxwell** [comment]
Wow man you really went to town on this lib. It's going to take me a while to review all these changes. Maybe we should make a website together someday!

**Comment by jkilpatrick15** [comment]
Hey @seanpmaxwell, sorry if I should have broken this up into multiple PR’s or should have posted here before trying to add features. I recently found this repo and  really like it and want to help wherever I can.

**Comment by joeykilpatrick** [comment]
@seanpmaxwell Bump

**Comment by seanpmaxwell** [comment]
Sorry I really need to get around to this. I haven't reviewed the changes but now that someone else has approved I should just implement it.

**Comment by seanpmaxwell** [comment]
Hey your changes broke the sample project in CustomRouterServer. Please fix before I update the library.
`super.addControllers(new CustomRouterController(), customRouter);`

Types of parameters 'handler' and 'handler' are incompatible.
          Types of parameters 'req' and 'req' are incompatible.
            Type 'import("c:/Projects/Overnight/sample-project/node_modules/@types/express-serve-static-core/index").Request' is not assignable to type 'import("c:/Projects/Overnight/src/core/node_modules/@types/express-serve-static-core/index").Request'.

**Comment by joeykilpatrick** [comment]
I am not able to reproduce this issue. Looks like you have two different versions of `@types/express-serve-static-core` installed, one in `src/core` and one in `sample-project`. I see now that the project-lock.json files have been gitignored, so I will commit a change to fix this and submit a new pull request.

**Comment by seanpmaxwell** [comment]
Oh yeah, I just updated the @types/express library is bother core and sample project and it's fixed. I redeployed overnight. Version for core is now 1.7.0

**Pull request merged**
